CREATE TABLE [dbo].[tbl_Inbound_Source_Setup] (
    [Inbound_Source_SetupID]            INT                                                IDENTITY (1, 1) NOT NULL,
    [Type_Of_Ingestion_LK_ID]           INT                                                NULL,
    [Source_URL]                        VARCHAR (500)                                      NULL,
    [User_ID]                           VARCHAR (50)                                       NULL,
    [Password]                          VARCHAR (50)                                       NULL,
    [Payroll_Provider_Type_LK_ID]       INT                                                NULL,
    [Frequency_ID]                      INT                                                NULL,
    [Destination_Setup_ID]              INT                                                NULL,
    [Connection_Port]                   VARCHAR (100)                                      NULL,
    [Source_Folder_Path]                VARCHAR (500)                                      NULL,
    [From_Email_ID]                     VARCHAR (100)                                      NULL,
    [API_Name]                          VARCHAR (500)                                      NULL,
    [File_Type_LK_ID]                   INT                                                NULL,
    [File_Name_Pattern]                 VARCHAR (200)                                      NULL,
    [Payroll_Provider_ID]               INT                                                NULL,
    [Delimiter]                         VARCHAR (50)                                       NULL,
    [Is_Column_Header_Available]        CHAR (1)                                           NULL,
    [Is_Header_Row_Available]           CHAR (1)                                           NULL,
    [Is_Column_Footer_Header_Available] CHAR (1)                                           NULL,
    [Is_Footer_Row_Available]           CHAR (1)                                           NULL,
    [Data_Header_Row]                   INT                                                NULL,
    [Data_Start_Row]                    INT                                                NULL,
    [Footer_Start_Row]                  INT                                                NULL,
    [Hierarchial_Data]                  CHAR (1)                                           NULL,
    [Get_Or_Put]                        VARCHAR (10)                                       NULL,
    [Is_Active]                         TINYINT                                            NULL,
    [Created_By]                        VARCHAR (100)                                      NULL,
    [Created_Date]                      DATETIME                                           NULL,
    [Updated_By]                        VARCHAR (100)                                      NULL,
    [Updated_Date]                      DATETIME                                           NULL,
    [SysStartTime]                      DATETIME2 (7) GENERATED ALWAYS AS ROW START HIDDEN CONSTRAINT [DF_SysStart] DEFAULT (sysutcdatetime()) NOT NULL,
    [SysEndTime]                        DATETIME2 (7) GENERATED ALWAYS AS ROW END HIDDEN   CONSTRAINT [DF_SysEnd] DEFAULT (CONVERT([datetime2],'9999-12-31 23:59:59.9999999')) NOT NULL,
    [Filename_Structure_Parts]          INT                                                NULL,
    [Storage_Folder_Name]               VARCHAR (100)                                      NULL,
    [Sheet_Name]                        VARCHAR (50)                                       NULL,
    PRIMARY KEY CLUSTERED ([Inbound_Source_SetupID] ASC),
    FOREIGN KEY ([Destination_Setup_ID]) REFERENCES [dbo].[tbl_Destination_Setup] ([Destination_Setup_ID]),
    FOREIGN KEY ([File_Type_LK_ID]) REFERENCES [dbo].[tbl_Lookup] ([Lookup_ID]),
    FOREIGN KEY ([Payroll_Provider_ID]) REFERENCES [dbo].[tbl_Payroll_Provider] ([Payroll_Provider_ID]),
    FOREIGN KEY ([Payroll_Provider_Type_LK_ID]) REFERENCES [dbo].[tbl_Lookup] ([Lookup_ID]),
    FOREIGN KEY ([Type_Of_Ingestion_LK_ID]) REFERENCES [dbo].[tbl_Lookup] ([Lookup_ID]),
    PERIOD FOR SYSTEM_TIME ([SysStartTime], [SysEndTime])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[dbo].[History_Inbound_Source_Setup], DATA_CONSISTENCY_CHECK=ON));

